@echo off
cd /d "%~dp0"
echo Removing stale git lock if present...
if exist ".git\index.lock" del ".git\index.lock"
echo Staging all changes...
git add -A
echo Committing...
git commit -m "Add Vercel MCP to Cursor config"
echo Pushing to GitHub...
git push origin main
echo.
echo Done! Press any key to close.
pause
