/** Airtable field display names — create these in your base (see README). */

export const A = {
  conversation: {
    conversationId: "Conversation ID",
    projectName: "Project Name",
    projectRoot: "Project Root",
    sourceType: "Source Type",
    sourcePath: "Source Path",
    sourceUrl: "Source URL",
    conversationTitle: "Conversation Title",
    conversationDate: "Conversation Date",
    importedAt: "Imported At",
    lastSyncedAt: "Last Synced At",
    contentHash: "Content Hash",
    dedupeKey: "Dedupe Key",
    status: "Status",
    agentName: "Agent Name",
    userRequest: "User Request",
    shortSummary: "Short Summary",
    detailedSummary: "Detailed Summary",
    keyOutcome: "Key Outcome",
    currentState: "Current State",
    filesChangedCount: "Files Changed Count",
    commandsRunCount: "Commands Run Count",
    errorsCount: "Errors Count",
    decisionsCount: "Decisions Count",
    actionItemsCount: "Action Items Count",
    tags: "Tags",
    relatedFeature: "Related Feature",
    relatedRoute: "Related Route",
    relatedApiEndpoint: "Related API Endpoint",
    relatedDatabaseTable: "Related Database Table",
    relatedMigration: "Related Migration",
    relatedProvider: "Related Provider",
    relatedUiPage: "Related UI Page",
    hasBuildOutput: "Has Build Output",
    hasTestOutput: "Has Test Output",
    hasErrors: "Has Errors",
    needsFollowUp: "Needs Follow-Up",
    rawTranscriptRedacted: "Raw Transcript Redacted",
    localRawFilePath: "Local Raw File Path",
    notionPageUrl: "Notion Page URL",
    linearIssuesCreated: "Linear Issues Created",
    syncNotes: "Sync Notes",
  },
  action: {
    actionId: "Action ID",
    conversationId: "Conversation ID",
    projectName: "Project Name",
    title: "Title",
    description: "Description",
    priority: "Priority",
    status: "Status",
    type: "Type",
    relatedFile: "Related File",
    relatedFeature: "Related Feature",
    suggestedOwner: "Suggested Owner",
    dueDate: "Due Date",
    linearIssueUrl: "Linear Issue URL",
    createdAt: "Created At",
    updatedAt: "Updated At",
    dedupeKey: "Dedupe Key",
    confidence: "Confidence",
  },
  fileRef: {
    fileRefId: "File Ref ID",
    conversationId: "Conversation ID",
    projectName: "Project Name",
    filePath: "File Path",
    mentionType: "Mention Type",
    changeType: "Change Type",
    summary: "Summary",
    existsLocally: "Exists Locally",
    createdAt: "Created At",
    dedupeKey: "Dedupe Key",
  },
  error: {
    errorId: "Error ID",
    conversationId: "Conversation ID",
    projectName: "Project Name",
    errorType: "Error Type",
    errorMessage: "Error Message",
    command: "Command",
    filePath: "File Path",
    resolution: "Resolution",
    status: "Status",
    createdAt: "Created At",
    dedupeKey: "Dedupe Key",
  },
  decision: {
    decisionId: "Decision ID",
    conversationId: "Conversation ID",
    projectName: "Project Name",
    decision: "Decision",
    rationale: "Rationale",
    relatedFeature: "Related Feature",
    relatedFile: "Related File",
    createdAt: "Created At",
    dedupeKey: "Dedupe Key",
  },
} as const;
