import type { FamilyEvent } from "@/lib/validation";

/** Deterministic demo data when Airtable is unavailable. */
export const MOCK_FAMILY_EVENTS: FamilyEvent[] = [
  {
    airtableRecordId: "mock_rec_01",
    eventName: "Toddler Storytime",
    date: isoDateDaysFromToday(0),
    startTime: "10:30",
    endTime: "11:15",
    city: "Rocklin",
    venue: "Rocklin Library",
    address: "4890 Granite Dr, Rocklin, CA",
    sourceName: "Roseville Public Library",
    sourceType: "Library",
    sourceLink: "https://www.placer.ca.gov/libraries",
    eventLink: "",
    ageRange: "0–5",
    cost: "",
    free: true,
    category: "Story Time",
    categoryPrefix: "STORY TIME",
    indoorOutdoor: "Indoor",
    recurring: true,
    registrationRequired: false,
    kidFriendlyNotes: "Songs + stories; stroller-friendly seating.",
    description: "",
    screenshotUrl: "",
    lastCheckedDate: new Date().toISOString(),
    status: "Confirmed",
    addedToGoogleCalendar: false,
    confidenceScore: 0.9,
  },
  {
    airtableRecordId: "mock_rec_02",
    eventName: "Family Movie Night Under the Stars",
    date: isoDateDaysFromToday(3),
    startTime: "19:00",
    endTime: "21:30",
    city: "Lincoln",
    venue: "Beermann Plaza",
    address: "",
    sourceName: "City of Lincoln",
    sourceType: "City Calendar",
    sourceLink: "https://www.lincolnca.gov/events",
    eventLink: "",
    ageRange: "All ages",
    cost: "",
    free: true,
    category: "Community",
    categoryPrefix: "FREE",
    indoorOutdoor: "Outdoor",
    recurring: false,
    registrationRequired: false,
    kidFriendlyNotes: "Bring blankets; snacks sold nearby.",
    description: "",
    status: "Need Review",
    addedToGoogleCalendar: false,
    confidenceScore: 0.62,
  },
  {
    airtableRecordId: "mock_rec_03",
    eventName: "Kids Science Saturday",
    date: isoDateDaysFromToday(6),
    startTime: "11:00",
    endTime: "14:00",
    city: "Sacramento",
    venue: "MOSAC",
    address: "400 Jibboom St, Sacramento, CA",
    sourceName: "MOSAC",
    sourceType: "Museum",
    sourceLink: "https://www.mosac.org",
    eventLink: "https://www.mosac.org/visit",
    ageRange: "5–12",
    cost: "$15 per person",
    free: false,
    category: "STEM",
    categoryPrefix: "STEM",
    indoorOutdoor: "Indoor",
    recurring: false,
    registrationRequired: true,
    kidFriendlyNotes: "Timed entry; plan 90 minutes.",
    description: "",
    status: "Confirmed",
    addedToGoogleCalendar: false,
    confidenceScore: 0.88,
  },
  {
    airtableRecordId: "mock_rec_04",
    eventName: "Sunrise Farmers Market (family activities)",
    date: isoDateDaysFromToday(10),
    startTime: "08:00",
    endTime: "13:00",
    city: "Citrus Heights",
    venue: "",
    address: "Sunrise Mall area, Citrus Heights, CA",
    sourceName: "Sunrise Marketplace",
    sourceType: "Market",
    sourceLink: "https://sunrisemarketplace.com/events",
    eventLink: "",
    ageRange: "All ages",
    cost: "Free entry",
    free: true,
    category: "Farmers Market",
    categoryPrefix: "MARKET",
    indoorOutdoor: "Outdoor",
    recurring: true,
    registrationRequired: false,
    kidFriendlyNotes: "",
    description: "",
    status: "Need Review",
    addedToGoogleCalendar: false,
    confidenceScore: 0.55,
  },
  {
    airtableRecordId: "mock_rec_05",
    eventName: "Zoo Preschool Safari",
    date: isoDateDaysFromToday(14),
    startTime: "09:30",
    endTime: "10:30",
    city: "Sacramento",
    venue: "Sacramento Zoo",
    address: "3930 W Land Park Dr, Sacramento, CA",
    sourceName: "Sacramento Zoo",
    sourceType: "Zoo",
    sourceLink: "https://www.saczoo.org",
    eventLink: "",
    ageRange: "3–5",
    cost: "Included with zoo admission",
    free: false,
    category: "Animals",
    categoryPrefix: "ZOO",
    indoorOutdoor: "Outdoor",
    recurring: false,
    registrationRequired: true,
    kidFriendlyNotes: "Small group; guardians required.",
    description: "",
    status: "Added to Calendar",
    addedToGoogleCalendar: true,
    googleCalendarEventId: "demo_google_evt_999",
    addedDate: new Date().toISOString(),
    confidenceScore: 0.91,
  },
];

function isoDateDaysFromToday(offsetDays: number): string {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
}
