import type { FamilyEventSource } from "@/lib/sources";

/** Deterministic demo sources used when Airtable is unavailable. */
export const MOCK_FAMILY_EVENT_SOURCES: FamilyEventSource[] = [
  {
    airtableRecordId: "mock_src_01",
    sourceName: "Sacramento4Kids Events Calendar",
    sourceType: "Regional calendar",
    cityArea: "Sacramento region",
    website: "https://sacramento4kids.com",
    facebook: "",
    sourceLink: "https://sacramento4kids.com",
    bestFor: "Family calendar roundups",
    priority: "High",
    active: true,
    lastCheckedDate: "",
    notes: "",
  },
  {
    airtableRecordId: "mock_src_02",
    sourceName: "Roseville City School District",
    sourceType: "School District",
    cityArea: "Roseville",
    website: "https://www.rcsdk8.org/",
    facebook: "",
    sourceLink: "https://www.rcsdk8.org/",
    bestFor: "District-wide events",
    priority: "Medium",
    active: true,
    lastCheckedDate: "",
    notes: "",
  },
  {
    airtableRecordId: "mock_src_03",
    sourceName: "Real Moms of Sac and Placer County (Facebook)",
    sourceType: "Facebook Group",
    cityArea: "Sacramento / Placer",
    website: "",
    facebook: "https://www.facebook.com/groups/example",
    sourceLink: "https://www.facebook.com/groups/example",
    bestFor: "Community-posted pop-ups",
    priority: "Medium",
    active: true,
    lastCheckedDate: "",
    notes: "Manual review only — verify before publishing.",
  },
  {
    airtableRecordId: "mock_src_04",
    sourceName: "BusyKids Play Town and Coffee Shop",
    sourceType: "Indoor Play",
    cityArea: "Roseville",
    website: "https://www.busykids.ca/",
    facebook: "",
    sourceLink: "https://www.busykids.ca/",
    bestFor: "Open play specials",
    priority: "Medium",
    active: true,
    lastCheckedDate: "",
    notes: "",
  },
  {
    airtableRecordId: "mock_src_05",
    sourceName: "Folsom Parks & Recreation",
    sourceType: "Parks & Rec",
    cityArea: "Folsom",
    website: "https://www.folsom.ca.us/parks",
    facebook: "",
    sourceLink: "https://www.folsom.ca.us/parks",
    bestFor: "Outdoor / weekend programming",
    priority: "High",
    active: true,
    lastCheckedDate: "",
    notes: "",
  },
];
